# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('usuario', '0003_textos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userf',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Userf',
        ),
    ]
