# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20180428_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='textos')),
            ],
        ),
        migrations.DeleteModel(
            name='Textos',
        ),
    ]
