# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20180428_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='archivo',
            field=models.FileField(null=True, upload_to='textos'),
        ),
    ]
