# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 21:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20180428_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='archivo',
            field=models.FileField(null=True, upload_to='textos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'pm2'])]),
        ),
    ]
