# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 04:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_texto_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='archivo',
            field=models.FileField(default=1, upload_to='textos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'pm2'])]),
            preserve_default=False,
        ),
    ]
